### ISSUE TITLE
Support randomized URL slug generation instead of "<ADJECTIVE>-<NAME>"?

### ISSUE THREAD

**Issue by acherunilam** [SinTan1729/chhoto-url#11]
**Is your feature request related to a problem? Please describe.**

Can we support server-side  randomized URL slug generation?

For aesthetic reasons, I want my shortened URLs to be really short (e.g., `/f4d0q`) and not long (e.g., `/festive-robinson`). For security reasons, I want it make it harder for an adversary to enumerate shortened URLs since "\<ADJECTIVE>-\<NAME>" has only ~26k possibilities.

**Describe the solution you'd like**

@mkaczanowski's [Pastebin](https://github.com/mkaczanowski/pastebin/tree/master), a popular self-hosted Pastebin written in Rust, [uses nanoid](https://github.com/mkaczanowski/pastebin/blob/master/src/main.rs#L357) to generate a randomized slug for a configurable character set and slug length. We can do the same?

I would prefer that both the character set and the slug length be customizable through environment variables or CLI args, but if you prefer to keep the character set [the same](https://github.com/SinTan1729/chhoto-url/blob/main/actix/src/utils.rs#L15) and make just the slug length configurable, I'm okay with that too. Maybe if none of these options are specified, we can default to the existing "\<ADJECTIVE>-\<NAME>" convention.

**Describe alternatives you've considered**

I considered delegating the randomized slug generation responsibility to the client, but it feels neater to handle it server-side.

**Comment by SinTan1729** [comment]
Hi @acherunilam, this should be easy to do. I'll get to it when I have some free time. If you have experience with Rust, I'm happy to accept PRs as well.

I plan to make the slug length configurable, and keep the same character set. Actually, for aesthetic reasons, it might be nice to simply use a-z and 0-9. It wouldn't matter too much in terms of security.

**Comment by SinTan1729** [comment]
The functionality in present in the latest release. Please look at the README and the `compose.yaml` file for instructions.
