### ISSUE TITLE
Text fragments break URI parsing in the UI

### ISSUE THREAD

**Issue by acherunilam** [SinTan1729/chhoto-url#14]
**Describe the bug**

If the long URL has a comma (e.g., within a [text fragment](https://developer.mozilla.org/en-US/docs/Web/Text_fragments)), then the UI shows wrong info.

**To Reproduce**
1. Start Chhoto URL.
```
docker run -p 4567:4567 -d sintan1729/chhoto-url:latest
```
2. Shorten a URL containing a text fragment.
```bash
curl 'http://localhost:4567/api/new' --data-raw 'https://github.com/SinTan1729/chhoto-url#:~:text=feel%20like%20a-,feature%20is%20missing,-%2C%20please%20let%20me'
```
3. Open `http://localhost:4567` in your browser, you'll see that the Hits column is incorrect - it shows part of the text fragment instead of the hit counter.

The UI makes [an assumption](https://github.com/SinTan1729/chhoto-url/blob/main/resources/static/script.js#L37) that the URI won't have a comma, which isn't always true. Maybe serialize the output of `/api/all` to JSON instead of comma-separated plaintext?

**Expected behavior**

I expect to see the hit counter for an entry in the UI.

**Screenshots**

<img width="1302" alt="uri-parsing-broken" src="https://github.com/SinTan1729/chhoto-url/assets/5555721/86d09535-d082-4088-bdc5-fc8ec3f55d17">

**Desktop (please complete the following information):**
 - OS: macOS 14.3.1
 - Browser: Safari 17.3.1

**Comment by SinTan1729** [comment]
You're right. This is a remnant of the old project. I do plan to rewrite this part.
