### ISSUE TITLE
Throw HTTP 400 if the API request is malformed instead of abruptly terminating the HTTP session

### ISSUE THREAD

**Issue by acherunilam** [SinTan1729/chhoto-url#16]
**Describe the bug**

If the server doesn't get the API request in the JSON form that [it expects](https://github.com/SinTan1729/chhoto-url/blob/main/actix/src/utils.rs#L35), it abruptly terminates the HTTP session instead of elegantly throwing an [HTTP 400](https://restfulapi.net/http-status-codes/#:~:text=Description-,400%20Bad%20Request,-The%20request%20could) to indicate a malformed request.

On a related note, the README in this repo [has a typo](https://github.com/SinTan1729/chhoto-url/blob/main/README.md?plain=1#L139) in the example client request .
```bash
# example request from README
# shhortlink -> shortlink
# <longlink> -> "<longlink>"
curl -X POST -d '{"shhortlink":"<shortlink>", "longlink":<longlink>}' http://localhost:4567/api/new
```

**To Reproduce**

1. Start Chhoto URL.
```bash
docker run -p 4567:4567 --name=chhoto-url -d sintan1729/chhoto-url:latest
```
2. Send a malformed request.
```bash
# typo in shortlink
curl -X POST -d '{"shhortlink":"", "longlink": "https://developer.mozilla.org/en-US/docs/Web/Text_fragments"}' http://localhost:4567/api/new
# curl: (52) Empty reply from server
```
3. Check the server logs.
```bash
docker logs -f chhoto-url
# thread 'actix-rt|system:0|arbiter:0' panicked at src/utils.rs:35:54:
# called `Result::unwrap()` on an `Err` value: Error("missing field `shortlink`", line: 1, column: 92)
# note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**

I expect an HTTP 400 to clearly indicate that the syntax is incorrect, and that the client shouldn't resend it without modifications.

**Comment by SinTan1729** [comment]
Thanks for opening the issue. This has already been dealt with in 38b817f, and is already available in the latest release.

**Comment by acherunilam** [comment]
@SinTan1729 Could you fix the [typo](https://github.com/SinTan1729/chhoto-url/blob/main/README.md?plain=1#L139) in the example client request in the README as well?

```bash
# example request from README
# shhortlink -> shortlink
# <longlink> -> "<longlink>"
curl -X POST -d '{"shhortlink":"<shortlink>", "longlink":<longlink>}' http://localhost:4567/api/new
```
