### ISSUE TITLE
API endpoint to edit the link

### ISSUE THREAD

**Issue by pythoninja** [SinTan1729/chhoto-url#19]
**Is your feature request related to a problem? Please describe.**
This is not an issue at all, but it will be good to just curl to edit the link.
My current use-case: I want to redirect with a permanent slug, say "current-preset" to the URL on S3 (which could be changed when I update the final file).

**Describe the solution you'd like**
`curl -X PUT -d '{"longlink": "https://newlink.com/file.json}' chhoto-url:4567/api/edit/<shortlink>`

Or something like that.

**Describe alternatives you've considered**
It's still possible to manually edit rows in the database.

**Comment by SinTan1729** [comment]
You can always just delete and recreate the link. This shouldn't be any different functionally, except for retaining the hit count.

**Comment by pythoninja** [comment]
Ok, thank you for your reply.
