### ISSUE TITLE
Add setting to disable link deletion

### ISSUE THREAD

**Issue by Elara6331** [SinTan1729/chhoto-url#20]
**Is your feature request related to a problem? Please describe.**
I'd like to run this as a public service, but that would allow users to delete other people's links

**Describe the solution you'd like**
I'd like an environment variable setting to disable link deletion. It might also be useful to be able to disable viewing active links.

**Describe alternatives you've considered**
There aren't any lightweight alternatives

**Comment by SinTan1729** [comment]
This is an interesting idea. But I have to think how I want to implement it. There should be some way of deleting and listing the links if this is enabled, but I don't want to go multi-user.

**Comment by SinTan1729** [comment]
Hi @Elara6331, I've made a PR addressing this. Can you do some testing and let me know if it's working properly? You can access the dev build using the docker tag `dev`.
