### ISSUE TITLE
Add cache control headers

### ISSUE THREAD

**Issue by luckman212** [SinTan1729/chhoto-url#22]
I love this project! 🙏 

Today I was struggling to figure out why some updated images I put in `/resources/assets` were still loading the old versions. I run Chhoto behind Cloudflare proxy, and apparently it [caches png and other static assets by default][1] if the webserver doesn't set the `Cache-Control` header to `private`, `no-store`, `no-cache`, or `max-age=0`. 

I see in the docs at https://docs.rs/actix-web/latest/actix_web/http/header/struct.CacheControl.html that there seems to be a fairly easy way to add these cache control headers. So that's what this request is about!

I am not sure if I am up to a full PR but if that is required I can try.

[1]: https://developers.cloudflare.com/cache/concepts/default-cache-behavior/

**Comment by SinTan1729** [comment]
Hi @luckman212, I think adding these header to the assets will be a good idea. Although, I'll probably add it as a configurable setting, enabled by default.

It's easy to add these to the responders. But the assets are served using a `actix_files::Files` struct. After a quick glance at the documentation, I couldn't find a way to add these headers to it.

**Comment by luckman212** [comment]
Ah I see. I'm not familiar with Actix or Rust much but seems like they have a plugin system called Middleware that allows for this.

example:

https://git.itsufficient.me/rust/actix-cachecontrol-middleware

**Comment by SinTan1729** [comment]
Can you test if the latest commit is working? The latest dev build can be accessed using the `dev` image tag.

**Comment by luckman212** [comment]
Thanks @SinTan1729 - I pulled from the `dev` tag and tested it but I don't think it's working. I don't see any cache-control directives in the header response:

<img width="773" alt="image" src="https://github.com/SinTan1729/chhoto-url/assets/1992842/ce9b7800-ef32-4dee-8235-5b0080c80d48">

**Comment by SinTan1729** [comment]
I'm a little confused. I am getting the correct header.
![image](https://github.com/SinTan1729/chhoto-url/assets/35728385/84ba129f-2019-4fd5-bf43-281247a02c31)
You're testing it locally, right? Can you maybe try force refreshing the page to make sure it's not using cached responses from before?

**Comment by SinTan1729** [comment]
I'm a little confused. I am getting the correct response header.
![image](https://github.com/SinTan1729/chhoto-url/assets/35728385/08fd65b7-c442-4e6a-b423-3785100958c4)
You're testing locally, right? Maybe try force refreshing the page to make sure the browser isn't using cached responses from earlier?

**Comment by luckman212** [comment]
Hmm I was testing from Chrome and tried shift+refresh which at least USED to force a cache miss but not sure it does any more... 

I tested in Safari just now, which I don't use and so should have a clean cache, and went directly to the docker container, bypassing Cloudflare proxy, and you're right I do see the header there. So, looks like it's working. Maybe I need to wait 24h for the existing cached content to flush out. Thanks for all this help. Seems to be working!

<img width="1003" alt="image" src="https://github.com/SinTan1729/chhoto-url/assets/1992842/388403c1-b03f-4fc7-b2fa-2384410f0df1">

**Comment by SinTan1729** [comment]
Happy to help. Now I just need to do some performance testing to figure out of I should keep the cache disabled by default, since no one would be changing the resources all that often in practice.

**Comment by SinTan1729** [comment]
Quick update: I changed it a bit. Now it sends no headers by default. To achieve what you want, pass `cache_control_header=no-cache, private` to the docker image.

**Comment by luckman212** [comment]
This is great, thank you again! 🙏
