### ISSUE TITLE
The 404 page is not responsive

### ISSUE THREAD

**Issue by trmdi** [SinTan1729/chhoto-url#23]
![Screenshot_2024-06-01-11-55-37-340-edit_com kiwibrowser browser](https://github.com/SinTan1729/chhoto-url/assets/11857205/8f0dcd89-63f6-4dd3-ae43-ed64691398d7)

**Comment by SinTan1729** [comment]
I don't understand the issue. Can you please elaborate?

**Comment by trmdi** [comment]
I use the latest version.
The issue is the text is too small on mobile.
It's missing the mobile scaling meta tag.

**Comment by SinTan1729** [comment]
Ah. 9948ce713c8ec124844f002a2cfab6f1100f5b25 should address it. This will be available when a new patch is released.
