### ISSUE TITLE
Add 'https://' on copy link

### ISSUE THREAD

**Issue by EliasB-NU** [SinTan1729/chhoto-url#25]
**Is your feature request related to a problem? Please describe.**
If I shorten a link and want to send it to friends, in for example a discord server/chat, I have to manual add the 'https://' handle before the link.

**Describe the solution you'd like**
Just add the 'https://' handle in front of the link on a copy link click

**Describe alternatives you've considered**
It doesn't seem to big of a change, so I haven't considered an alternative. 

**Additional context**
I think it is clear.

Hope you can implement something like that.

**Comment by SinTan1729** [comment]
Hi! Do you have a single fixed public address for your site? If yes, you can set `site_url` in your `compose` file. Make sure that `https://` is added there. If not, accessing the admin page using that same address over `https` should also work.

**Comment by EliasB-NU** [comment]
Ah, works, thank you!
