### ISSUE TITLE
Make Index page more customizable

### ISSUE THREAD

**Issue by Aymendje** [SinTan1729/chhoto-url#26]
**Is your feature request related to a problem? Please describe.**
The page Title, icon and main header all say "Chhoto URL"
While I love this project, some of the users I share my link with dont necessarily understand what is the purpose of the website. Something like "URL shortener" or a custom message would be great.

**Describe the solution you'd like**
Ideally some kind of environment variables (or config file) where we could set the URL for the logo, the favicon, the title and the main header would be great. Environment variables might be easier, and would play nicely with docker too.

**Describe alternatives you've considered**
I could run my own static Index.html or a patch on the index.html, but I would prefer a supported feature instead when possible

**Additional context**
To not remove any credit, we can keep a footer with something like "Powered by Chhoto" or "Made with love @ Chooto" with the Github URL
Some of my users are not very tech savvy and get worried its a suspicious website when they dont understand what they see...
Again, thank you so much for your wonderful work !

Current :
![image](https://github.com/user-attachments/assets/97c06bd9-89ff-48c3-974e-927cfebd2243)

Ideal :
![image](https://github.com/user-attachments/assets/dd159718-fbe9-4da2-82f3-5ea4079b3534)

**Comment by beucismis** [comment]
Dark theme support?

**Comment by SinTan1729** [comment]
@beucismis It works well with Dark Reader.

**Comment by SinTan1729** [comment]
Relevant release 7.6.0
