### ISSUE TITLE
Feature: Docker Healthcheck

### ISSUE THREAD

**Issue by yilmaz08** [SinTan1729/chhoto-url#28]
**Is your feature request related to a problem? Please describe.**
Currently, chhoto-url docker doesn't have a healthcheck in it. Which is (I believe) an important feature for a docker container.

**Describe the solution you'd like**
My solution is to move away from using "scratch" as the base since it doesn't provide necessary packages for a simple healthcheck (sh and curl). However this would make the container bigger in size and overall less minimalist.

**Describe alternatives you've considered**
Maybe the necessary packages can be copied from the "builder". I've tried this but copying sh caused errors I couldn't fix. However, if someone else can add a healthcheck with something like this, it would be much better than my solution.

**Comment by SinTan1729** [comment]
For an image that doesn't connect to the internet for anything, I don't see the point of doing a `healthcheck`. What would the `healthcheck` check?

**Comment by yilmaz08** [comment]
The `healthcheck` could execute something like `curl -f http://localhost:4567/` and it would be useful in cases where the web server doesn't function properly although the container is up.

**Comment by SinTan1729** [comment]
I think that's superfluous as it doesn't actually check anything. The vast majority of the docker images I run do not use `healthcheck`, and I don't see a point in using it here either.

Add to that the fact that there's already a good amount of error handling built into the application, and I've never had any downtime using it. If you actually encounter any errors that can only be detected with a `healthcheck`, feel free to reopen the issue. For now, I'm closing it as not planned.
