### ISSUE TITLE
ARM support?

### ISSUE THREAD

**Issue by halictuz** [SinTan1729/chhoto-url#9]
Hi. Great project. 

Is there a chance to have a docker for arm/arm64 ? Would love to run this on RPI or certain arm vps.

Thanks for your work

greetings

**Comment by SinTan1729** [comment]
In theory, it should be as easy as adding an extra build target. But I don't have any arm devices to test on. If you're willing to help me with some testing, I can try to get it to work.

**Comment by SinTan1729** [comment]
Hi @halictuz, did you manage to do some testing?

**Comment by SinTan1729** [comment]
I'll start uploading the arm build, so closing this issue. If you're having any issues with the builds, feel free to reopen it.
